<?xml version="1.0" encoding="UTF-8"?><testsuite errors="0" failures="2" name="com.gorest.testsuits.UserDataDrivenTest" skipped="0" tests="8" time="5.44" timestamp="2023-01-10T19:51:41.289Z[Europe/London]"><testcase classname="com.gorest.testsuits.UserDataDrivenTest" name="Data Driven test for creating multiple users"><failure message="1 expectation failed.&#10;Expected status code &lt;201&gt; but was &lt;422&gt;.&#10;" type="java.lang.AssertionError">1 expectation failed.
Expected status code &lt;201&gt; but was &lt;422&gt;.
</failure><system-err>1 expectation failed.
Expected status code &lt;201&gt; but was &lt;422&gt;.
&#13;
io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:636)&#13;
io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:122)&#13;
io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:130)&#13;
io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)&#13;
com.gorest.testsuits.UserDataDrivenTest.createMultipleUsersFromData(UserDataDrivenTest.java:31)&#13;
</system-err></testcase></testsuite>